/**
 * D191 — a catalogue as data, and the one function that applies it.
 *
 * ## Why this exists
 *
 * `mock-catalog.ts` proved the shape the hardware tenant wanted: pure data, no
 * runtime dependencies, safe to import from the Prisma seed and the API alike.
 * Retail could not reuse it, because a hardware product is a row and a clothing
 * product is a row plus dimensions plus options plus a variant per combination
 * plus a stock row per variant. So the data needed a richer shape and the
 * writing needed a function.
 *
 * The split is deliberate and is the whole point of the file:
 *
 *  - **`mock-clothing.ts` / `mock-grocery.ts` are DATA.** Generated by
 *    `prisma/export-catalogue.ts` from a real workspace, never hand-edited.
 *    Reviewing them is reading a product list.
 *  - **`seedCatalogue` is BEHAVIOUR.** Written once, reviewed once. A bug here
 *    is fixed in one place for every pack.
 *
 * `seed-packs/clothing.ts` is NOT replaced and is not the same thing. That is
 * the **provisioning starter kit** a brand-new shop is handed — five empty
 * categories and two token products, deliberately thin because a real shop has
 * to delete whatever we invent (D120). This is the **demo catalogue** a
 * developer reviews in, which has the opposite requirement: it should look like
 * a shop that has been trading.
 *
 * ## Idempotent by natural key, never by id
 *
 * Every lookup here is by the key a human would use — a category's name, a
 * product's SKU, a dimension's name. Ids are generated, so a pack cannot carry
 * them and a re-seed cannot match on them. This is why re-running the seed
 * converges instead of stacking a second catalogue, and why a developer can
 * rename a seeded product in the app without the next seed creating a duplicate
 * beside it (it matches the SKU and renames it back).
 */
import type { Prisma, PrismaClient, QuantityType } from '@prisma/client';

type Db = PrismaClient | Prisma.TransactionClient;

/**
 * A two-part map key that cannot be forged by the names it joins.
 *
 * Joining on a space or a slash is wrong here and quietly so: category
 * `Men Wear` + subcategory `Shirts` and category `Men` + subcategory
 * `Wear Shirts` would produce the same key, and one shop's subcategory would
 * silently become another's. `JSON.stringify` escapes the separator out of the
 * parts, so the pair round-trips whatever a shopkeeper types.
 */
function key2(a: string, b: string): string {
  return JSON.stringify([a, b]);
}

/** One option combination of a product — the row the till actually sells. */
export interface CatalogueVariant {
  sku: string;
  barcode?: string;
  unitPrice: number;
  costPrice?: number;
  /** Dimension name → option name, e.g. `{ Size: 'M', Colour: 'Black' }`. */
  options: Record<string, string>;
  /** Stock at the pack's branch. D121 tracks stock by VARIANT, not product. */
  quantityOnHand?: number;
  isDefault?: boolean;
}

/** A variation axis and the values it offers, e.g. Size → S, M, L. */
export interface CatalogueDimension {
  name: string;
  options: string[];
}

export interface CatalogueProduct {
  name: string;
  sku?: string;
  /** QuickBooks item type: `Inventory` | `NonInventory` | `Service`. */
  type: string;
  description?: string;
  /** Category name; created if absent. `subcategory` nests under it. */
  category?: string;
  subcategory?: string;
  /** D133 — brand is an entity. Created per tenant on first use. */
  brand?: string;
  unitPrice: number;
  costPrice?: number;
  quantityType?: QuantityType;
  unitOfMeasure?: string;
  reorderLevel?: number;
  /** D64 — description lives here; behaviour lives in columns. */
  attributes?: Record<string, unknown>;
  taxable?: boolean;
  /**
   * Stock for a VARIANT-LESS product only. D121 keeps `Product.quantityOnHand`
   * in its D10 role for these; a product with variants carries stock per
   * variant and this field is ignored.
   */
  quantityOnHand?: number;
  dimensions?: CatalogueDimension[];
  variants?: CatalogueVariant[];
}

export interface CataloguePack {
  /**
   * Top-level categories in display order, including any a product does not
   * reference. A shop's category rail is part of its shape.
   */
  categories: readonly string[];
  products: readonly CatalogueProduct[];
}

export interface CatalogueResult {
  categories: number;
  products: number;
  variants: number;
  stockRows: number;
}

/**
 * Write a pack into a tenant, converging rather than duplicating.
 *
 * `branchId` is where stock lands. A pack has no opinion about branches: the
 * same catalogue seeded into a two-branch tenant would be stocked twice, which
 * is the caller's decision to make and not the data's.
 */
export async function seedCatalogue(
  db: Db,
  tenantId: string,
  branchId: string,
  pack: CataloguePack,
): Promise<CatalogueResult> {
  const result: CatalogueResult = { categories: 0, products: 0, variants: 0, stockRows: 0 };

  // ── categories ─────────────────────────────────────────────────────────────
  const categoryIds = new Map<string, string>();
  const named = new Set<string>(pack.categories);
  for (const p of pack.products) if (p.category) named.add(p.category);

  // `pack.categories` first and in order, so the rail a shop arranged survives;
  // anything a product references but the list forgot is appended after.
  const ordered = [...pack.categories, ...[...named].filter((n) => !pack.categories.includes(n))];
  for (const [index, name] of ordered.entries()) {
    const existing = await db.productCategory.findFirst({ where: { tenantId, name } });
    const row =
      existing ??
      (await db.productCategory.create({
        data: { tenantId, name, sortOrder: index, isActive: true },
      }));
    categoryIds.set(name, row.id);
    result.categories += 1;
  }

  // ── subcategories ──────────────────────────────────────────────────────────
  const subcategoryIds = new Map<string, string>();
  for (const p of pack.products) {
    if (!p.subcategory || !p.category) continue;
    const key = key2(p.category, p.subcategory);
    if (subcategoryIds.has(key)) continue;
    const categoryId = categoryIds.get(p.category);
    if (!categoryId) continue;
    const existing = await db.productSubcategory.findFirst({
      where: { tenantId, categoryId, name: p.subcategory },
    });
    const row =
      existing ??
      (await db.productSubcategory.create({
        data: { tenantId, categoryId, name: p.subcategory, isActive: true },
      }));
    subcategoryIds.set(key, row.id);
  }

  // ── brands (D133) ──────────────────────────────────────────────────────────
  const brandIds = new Map<string, string>();
  for (const p of pack.products) {
    if (!p.brand || brandIds.has(p.brand)) continue;
    const existing = await db.brand.findFirst({ where: { tenantId, name: p.brand } });
    const row =
      existing ?? (await db.brand.create({ data: { tenantId, name: p.brand, isActive: true } }));
    brandIds.set(p.brand, row.id);
  }

  // ── products ───────────────────────────────────────────────────────────────
  for (const [index, p] of pack.products.entries()) {
    const hasVariants = (p.variants?.length ?? 0) > 0;

    const shared = {
      name: p.name,
      type: p.type,
      description: p.description ?? null,
      categoryId: p.category ? (categoryIds.get(p.category) ?? null) : null,
      subcategoryId:
        p.subcategory && p.category
          ? (subcategoryIds.get(key2(p.category, p.subcategory)) ?? null)
          : null,
      brandId: p.brand ? (brandIds.get(p.brand) ?? null) : null,
      unitPrice: p.unitPrice,
      costPrice: p.costPrice ?? null,
      ...(p.quantityType ? { quantityType: p.quantityType } : {}),
      unitOfMeasure: p.unitOfMeasure ?? null,
      reorderLevel: p.reorderLevel ?? null,
      attributes: (p.attributes ?? {}) as Prisma.InputJsonValue,
      ...(p.taxable === undefined ? {} : { taxable: p.taxable }),
      hasVariants,
      /*
       * D121 — for a product WITH variants this column is a legacy fallback
       * that is not read, so it is left at 0 rather than filled with a rollup
       * that would go stale. For a variant-less product it keeps its D10 role
       * and is the number the till reads.
       */
      quantityOnHand: hasVariants ? 0 : (p.quantityOnHand ?? 0),
      isActive: true,
    };

    // Matched by SKU where there is one, by name otherwise: `@@unique([tenantId,
    // sku])` makes SKU the real identity, but a service or a loose grocery line
    // legitimately has none.
    const existing = p.sku
      ? await db.product.findFirst({ where: { tenantId, sku: p.sku } })
      : await db.product.findFirst({ where: { tenantId, name: p.name, sku: null } });

    const product = existing
      ? await db.product.update({ where: { id: existing.id }, data: shared })
      : await db.product.create({ data: { tenantId, sku: p.sku ?? null, ...shared } });
    result.products += 1;

    if (!hasVariants) {
      if (p.quantityOnHand !== undefined) {
        await upsertStock(db, tenantId, branchId, product.id, null, p.quantityOnHand);
        result.stockRows += 1;
      }
      continue;
    }

    // ── dimensions and their options ─────────────────────────────────────────
    const optionIds = new Map<string, { dimensionId: string; optionId: string }>();
    for (const [dIndex, dim] of (p.dimensions ?? []).entries()) {
      const existingDim = await db.productVariationDimension.findFirst({
        where: { productId: product.id, name: dim.name },
      });
      const dimension =
        existingDim ??
        (await db.productVariationDimension.create({
          data: { tenantId, productId: product.id, name: dim.name, position: dIndex },
        }));

      for (const [oIndex, optionName] of dim.options.entries()) {
        const existingOpt = await db.productVariationOption.findFirst({
          where: { dimensionId: dimension.id, name: optionName },
        });
        const option =
          existingOpt ??
          (await db.productVariationOption.create({
            data: { tenantId, dimensionId: dimension.id, name: optionName, position: oIndex },
          }));
        optionIds.set(key2(dim.name, optionName), {
          dimensionId: dimension.id,
          optionId: option.id,
        });
      }
    }

    /*
     * ── which variant is the default ───────────────────────────────────────
     *
     * `ProductVariant_productId_default_key` is a PARTIAL unique index:
     *
     *     CREATE UNIQUE INDEX ... ON "ProductVariant" ("productId")
     *       WHERE ("isDefault" = true)
     *
     * so a product may have exactly ONE default variant. Prisma cannot express
     * a partial index, which is why the schema does not declare it and why
     * nothing in the type system stops a second one — it fails at the database
     * with a `P2002` naming `productId`, which reads like a duplicate product.
     *
     * Decided once per product rather than per variant. Asking each variant in
     * turn "are you the default, or are you index 0?" makes the pack's own
     * declared default AND index 0 both true, which is the exact bug this
     * comment replaced.
     *
     * A product with NO declared default gets none. The index forbids two
     * defaults, not zero, and every product in the exported shops has zero —
     * so falling back to "index 0 wins" would invent a fact the source never
     * stated, and a pack that invents is a pack that cannot be trusted to
     * reproduce the shop it came from.
     */
    const declared = (p.variants ?? []).findIndex((v) => v.isDefault === true);
    const defaultIndex = declared >= 0 ? declared : -1;
    let defaultVariantId: string | null = null;

    // ── variants ─────────────────────────────────────────────────────────────
    for (const [vIndex, v] of (p.variants ?? []).entries()) {
      const existingVariant = await db.productVariant.findFirst({
        where: { tenantId, sku: v.sku },
      });
      const variantData = {
        productId: product.id,
        barcode: v.barcode ?? null,
        unitPrice: v.unitPrice,
        costPrice: v.costPrice ?? null,
        position: vIndex,
        isActive: true,
        /*
         * Every variant is written NOT-default and the winner is promoted after
         * the loop. Writing the flag here would mean that a re-seed which moves
         * the default from variant 3 to variant 1 sets 1 true while 3 is still
         * true — momentarily two defaults, and the partial index refuses it.
         * The old default has to be cleared before the new one is set, and that
         * cannot happen inside a loop over one variant at a time.
         */
        isDefault: false,
      };
      const variant = existingVariant
        ? await db.productVariant.update({ where: { id: existingVariant.id }, data: variantData })
        : await db.productVariant.create({ data: { tenantId, sku: v.sku, ...variantData } });
      result.variants += 1;
      if (vIndex === defaultIndex) defaultVariantId = variant.id;

      /*
       * `ProductVariant` has NO `name` column — its readable name is derived
       * from the options it carries. Create a variant without these rows and
       * `variantDisplayName` falls back to the SKU, so the picker shows
       * `TSHIRT-M-BLACK` where it should show `Black / Medium`. The fallback is
       * deliberate, which is exactly why the mistake is silent.
       */
      for (const [dimName, optionName] of Object.entries(v.options)) {
        const ids = optionIds.get(key2(dimName, optionName));
        if (!ids) continue;
        const link = await db.productVariantOptionValue.findFirst({
          where: { variantId: variant.id, dimensionId: ids.dimensionId },
        });
        if (link) {
          if (link.optionId !== ids.optionId) {
            await db.productVariantOptionValue.update({
              where: { id: link.id },
              data: { optionId: ids.optionId },
            });
          }
          continue;
        }
        await db.productVariantOptionValue.create({
          data: {
            tenantId,
            variantId: variant.id,
            dimensionId: ids.dimensionId,
            optionId: ids.optionId,
          },
        });
      }

      if (v.quantityOnHand !== undefined) {
        await upsertStock(db, tenantId, branchId, product.id, variant.id, v.quantityOnHand);
        result.stockRows += 1;
      }
    }

    // Every variant above was written not-default, so exactly one row changes
    // here and the partial unique index never sees two at once.
    if (defaultVariantId) {
      await db.productVariant.update({
        where: { id: defaultVariantId },
        data: { isDefault: true },
      });
    }

    void index;
  }

  return result;
}

/**
 * `BranchInventory` has no unique index covering
 * `(tenantId, branchId, productId, productVariantId)` — `productVariantId` is
 * nullable and Postgres would treat two NULLs as distinct anyway — so this is a
 * lookup-then-write rather than an upsert. Without the lookup a re-seed stacks
 * a second stock row and the till reads whichever it finds first.
 */
async function upsertStock(
  db: Db,
  tenantId: string,
  branchId: string,
  productId: string,
  productVariantId: string | null,
  quantityOnHand: number,
): Promise<void> {
  const existing = await db.branchInventory.findFirst({
    where: { tenantId, branchId, productId, productVariantId },
    select: { id: true },
  });
  if (existing) {
    await db.branchInventory.update({ where: { id: existing.id }, data: { quantityOnHand } });
    return;
  }
  await db.branchInventory.create({
    data: { tenantId, branchId, productId, productVariantId, quantityOnHand },
  });
}
